package io.nuabo.hikitty.user.mock;


import io.nuabo.common.domain.exception.ResourceNotFoundException;
import io.nuabo.hikitty.user.application.port.UserRepository;
import io.nuabo.hikitty.user.domain.User;
import io.nuabo.hikitty.user.domain.UserStatus;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicLong;

public class FakeUserRepository implements UserRepository {

    private final AtomicLong autoGeneratedId = new AtomicLong(0);
    private final List<User> data = new ArrayList<>();


    @Override
    public User getById(long id) {
        return data.stream().filter(item -> item.getId().equals(id)).findAny().orElseThrow(()->
                new ResourceNotFoundException("Users", id));
    }

    @Override
    public Optional<User> findByEmailAndStatus(String email, UserStatus active) {
        return data.stream().filter(item->item.getEmail().equals(email) && item.getStatus() == active).findFirst();
    }

    @Override
    public Optional<User> findByIdAndStatus(long id, UserStatus active) {
        return data.stream().filter(item->item.getId().equals(id) && item.getStatus() == active).findFirst();
    }

    @Override
    public User save(User user) {
        if (user.getId() == null || user.getId() == 0) {
            User newUser = User.builder()
                    .id(autoGeneratedId.incrementAndGet())
                    .email(user.getEmail())
                    .name(user.getName())
                    .role(user.getRole())
                    .password(user.getPassword())
                    .status(user.getStatus())
                    .certificationCode(user.getCertificationCode())
                    .lastLoginAt(user.getLastLoginAt())
                    .build();
            data.add(newUser);
            return newUser;
        } else {
            data.removeIf(item -> Objects.equals(item.getId(), user.getId()));
            data.add(user);
            return user;
        }
    }

    @Override
    public Optional<User> findById(long id) {
        return data.stream().filter(item -> item.getId().equals(id)).findAny();
    }

    @Override
    public Optional<User> findByEmail(String email) {
        return data.stream().filter(item -> item.getEmail().equals(email)).findAny();
    }

    @Override
    public User getByEmailAndStatus(String email, UserStatus active) {
        return findByEmailAndStatus(email, active).orElseThrow(()->
                new ResourceNotFoundException("Users", email));
    }

    @Override
    public User getByIdAndStatus(Long fundraiserId, UserStatus active) {
        return data.stream().filter(item->item.getId().equals(fundraiserId) && item.getStatus() == active).findFirst().orElseThrow(()->
                new ResourceNotFoundException("Users", fundraiserId));
    }
}
