payment:
  toss:
    client-api-key: ${payment.toss.client-api-key}
    client-secret-key: ${payment.toss.client-secret-key}
    success-url: ${payment.toss.success-url}
    fail-url: ${payment.toss.fail-url}
    origin-url: ${payment.toss.origin-url}