cloud:
  aws:
    region:
      static: ap-northeast-2
      auto: false
    credentials:
      access-key: ${amazons3.accessKey}
      secret-key: ${amazons3.secretKey}
    s3:
      bucket: ${amazons3.bucket}

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB