spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url:  jdbc:h2:tcp://localhost/~/test;MODE=MySQL

    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

