name: todo-main-to-beanstalk

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest # The type of machine to run on

    steps:
      - name: Checkout source code # This step checks out a copy of your repository.
        uses: actions/checkout@v2 # Checks out your repository under $GITHUB_WORKSPACE, so your workflow can access it

      - name: Set up JDK 17 # JDK 설치
        uses: actions/setup-java@v1 # (5)
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        working-directory: ./
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        working-directory: ./
        run: ./gradlew clean build
        shell: bash

      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDDTHHmm
          utcOffset: "+09:00"

      - name: Generate deployment package
        run: |
          mkdir -p deploy
          cp ./build/libs/hi-kitty-1.jar deploy/todo-application-prod-ebextensions-1.jar
          cp Procfile deploy/Procfile
          cp -r .ebextensions deploy/.ebextensions
          cd deploy && zip -r todo-application-prod-label-${{steps.current-time.outputs.formattedTime}}-${{github.sha}}.zip
          
          - name: Deploy Consumer to EB
          uses: einaregilsson/beanstalk-deploy@v20
          with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: hiKitty
          environment_name: HiKitty-env
          version_label: todo-application-prod-label-${{steps.current-time.outputs.formattedTime}}-${{github.sha}}
          region: ap-northeast-2
          deployment_package: deploy/todo-application-prod-label-${{steps.current-time.outputs.formattedTime}}-${{github.sha}}.zip